config/routes.rb
Rails.application.routes.draw do

  resources :users

  get "/", to: "tasks#index", as: 'tasks'
  post "/", to: "tasks#create"

  get 'sessions/new'
  resources :tags
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :tasks, except: [:index]

  #admin routes
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tasks
  has_one :user
  has_many :taggings, dependent: :delete_all
  has_many :tagging_tasks, through: :taggings, source: :task


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy ]

  def index
    @tags = @current_user.tags
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = @current_user.tags.build(tag_params)
    if @tag.save
      redirect_to tags_path, notice: "Tag was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end



  def update
      if @tag.update(tag_params)
        redirect_to tags_path, notice: "Tag was successfully updated."
      else
         render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: "Tag was successfully destroyed."
  end


  private
  def set_tag
    @tag = Tag.find(params[:id])
  end
  def tag_params
   params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="row col-md-6">
<%= form_with(model: @tag, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary left-marge' %>
  </div>
<% end %>



<div>

app/views/tags/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', task: @tag %>

<%= link_to 'Show', @tag , class: 'btn btn-primary left-marge', style: "color: white;"%> |
<%= link_to 'Back', tags_path, class: 'btn btn-success left-marge', style: "color: white;" %>

app/views/tags/index.html.erb
<h1>General Label list</h1>

<div class="row">
	<%= link_to 'New Tag', new_tag_path, class: 'btn btn-primary left-marge', style: "color: white;" %>

</div>

<table class="table">
  <thead>
    <tr>
      <th  scope="col">Name</th>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td class="task_row"><%= tag.name %></td>
        <td><%= link_to 'Show', tag, class: 'show_link clear_link' %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag), class: 'edit_link clear_link' %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } , class: 'destroy_method clear_link'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tags/new.html.erb
<h1>New Label</h1>

<%= render 'form', task: @tag %>

<%= link_to 'Back', tags_path, class: 'btn btn-success text-white left-marge', style: 'color: white;' %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th  scope="col">Name</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @tag.name %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_tag_path(@tag), class: 'btn btn-primary text-white left-marge' %> |
<%= link_to 'Back', tags_path, class: 'btn btn-success text-white left-marge' %>