config/routes.rb
Rails.application.routes.draw do

  resources :users

  get "/", to: "tasks#index", as: 'tasks'
  post "/", to: "tasks#create"

  get 'sessions/new'
  resources :tags
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :tasks, except: [:index]

  #admin routes
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="container">
      <% if logged_in? %>
        <div class="row ">
          <header>
            <ul class="nav nav-pills" style="background-color: #f4f5f7;">
              <li class="">
                <a class="nav-link" href="#">Task_Management</a>
              </li>
              <li><%= link_to "Task registration", new_task_path %></li>
              <li><%= link_to "Task list", tasks_path %></li>
              <li><%= link_to "Label management", tags_path %></li>
              <li><%= link_to "account", user_path(@current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
               <% if @current_user.admin %>
                <li>
                  <%= link_to "Users management", admin_users_path %>
                </li>
               <% end %>
            </ul>
          </header>
      <% else  %>
      <%= link_to "Sign up", new_user_path, class: 'btn btn-primary', style: 'color: white' %>
      <%= link_to "Login", new_session_path, class: 'btn btn-success', style: 'color: white' %>
      <% end %>
    </div>

    <div class="flash">
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>

    <%= yield %>

    </div>
    <div class="container">
      <footer class="row row-cols-5 py-5 my-5 border-top">
        <p class="text-muted copyrigth">© 2021</p>
     </footer>
    </div>




  </body>
</html>